apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: weather-app-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      containers:
      - name: weather-app
        image: <yourdockerhub>/flask-weather-app:v0.1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:  
  name: weather-app
spec:
  selector:    
    app: weather-app
  type: NodePort
  ports:  
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
